import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PlanDetailsPage } from "@/components/plan-details-page";

// Dummy data for plans
const planData = {
  usa: {
    name: "United States",
    flag: "🇺🇸",
    type: "country",
    region: "North America",
    description:
      "Stay connected across the United States with our reliable eSIM plans. Perfect for business trips, vacations, or extended stays.",
    coverage: "Nationwide coverage including all 50 states",
    network: "T-Mobile, AT&T, Verizon",
    startingFrom: 5,
    plansCount: 3,
    plans: [
      {
        id: "usa-3gb-7d",
        name: "USA 3GB – 7 Days",
        price: 5,
        data: "3GB",
        validity: "7 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "No roaming charges", "24/7 support"],
      },
      {
        id: "usa-5gb-30d",
        name: "USA 5GB – 30 Days",
        price: 12,
        data: "5GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Instant activation",
          "No roaming charges",
          "24/7 support",
          "Most popular",
        ],
      },
      {
        id: "usa-10gb-30d",
        name: "USA 10GB – 30 Days",
        price: 20,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Instant activation",
          "No roaming charges",
          "24/7 support",
          "Best value",
        ],
      },
    ],
  },
  uk: {
    name: "United Kingdom",
    flag: "🇬🇧",
    type: "country",
    region: "Europe",
    description:
      "Stay connected throughout the UK with our comprehensive eSIM plans covering England, Scotland, Wales, and Northern Ireland.",
    coverage: "England, Scotland, Wales, Northern Ireland",
    network: "EE, O2, Three, Vodafone",
    startingFrom: 8,
    plansCount: 4,
    plans: [
      {
        id: "uk-2gb-7d",
        name: "UK 2GB – 7 Days",
        price: 8,
        data: "2GB",
        validity: "7 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "No roaming charges", "24/7 support"],
      },
      {
        id: "uk-5gb-15d",
        name: "UK 5GB – 15 Days",
        price: 15,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Instant activation",
          "No roaming charges",
          "24/7 support",
          "Most popular",
        ],
      },
      {
        id: "uk-10gb-30d",
        name: "UK 10GB – 30 Days",
        price: 25,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "No roaming charges", "24/7 support"],
      },
      {
        id: "uk-unlimited-30d",
        name: "UK Unlimited – 30 Days",
        price: 35,
        data: "Unlimited",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Unlimited data",
          "No roaming charges",
          "24/7 support",
          "Best value",
        ],
      },
    ],
  },
  japan: {
    name: "Japan",
    flag: "🇯🇵",
    type: "country",
    region: "Asia",
    description:
      "Stay connected in Japan with our reliable eSIM plans covering all major cities and regions.",
    coverage: "All major cities and regions",
    network: "NTT Docomo, SoftBank, KDDI",
    startingFrom: 12,
    plansCount: 3,
    plans: [
      {
        id: "japan-3gb-7d",
        name: "Japan 3GB – 7 Days",
        price: 12,
        data: "3GB",
        validity: "7 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Instant activation",
          "Reliable networks",
          "No roaming charges",
        ],
      },
      {
        id: "japan-5gb-15d",
        name: "Japan 5GB – 15 Days",
        price: 18,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Instant activation",
          "No roaming charges",
          "Best for travelers",
        ],
      },
      {
        id: "japan-10gb-30d",
        name: "Japan 10GB – 30 Days",
        price: 30,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "Best value", "24/7 support"],
      },
    ],
  },
  australia: {
    name: "Australia",
    flag: "🇦🇺",
    type: "country",
    region: "Oceania",
    description:
      "Stay connected in Australia with coverage across major cities and regional areas.",
    coverage: "Major cities and regional areas",
    network: "Telstra, Optus, Vodafone AU",
    startingFrom: 15,
    plansCount: 2,
    plans: [
      {
        id: "australia-5gb-15d",
        name: "Australia 5GB – 15 Days",
        price: 15,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "Instant activation",
          "Reliable coverage",
          "No roaming charges",
        ],
      },
      {
        id: "australia-10gb-30d",
        name: "Australia 10GB – 30 Days",
        price: 25,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Best value", "No roaming charges", "24/7 support"],
      },
    ],
  },
  canada: {
    name: "Canada",
    flag: "🇨🇦",
    type: "country",
    region: "North America",
    description:
      "Stay connected in Canada with coast-to-coast nationwide eSIM coverage.",
    coverage: "Coast to coast coverage",
    network: "Rogers, Bell, Telus",
    startingFrom: 10,
    plansCount: 3,
    plans: [
      {
        id: "canada-3gb-7d",
        name: "Canada 3GB – 7 Days",
        price: 10,
        data: "3GB",
        validity: "7 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "No roaming charges", "24/7 support"],
      },
      {
        id: "canada-5gb-15d",
        name: "Canada 5GB – 15 Days",
        price: 18,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "Reliable coverage", "Most popular"],
      },
      {
        id: "canada-10gb-30d",
        name: "Canada 10GB – 30 Days",
        price: 28,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Best value", "No roaming charges", "24/7 support"],
      },
    ],
  },
  germany: {
    name: "Germany",
    flag: "🇩🇪",
    type: "country",
    region: "Europe",
    description:
      "Reliable eSIM coverage across Germany with premium local networks.",
    coverage: "Nationwide 4G/5G coverage",
    network: "Telekom, Vodafone DE, O2 DE",
    startingFrom: 6,
    plansCount: 4,
    plans: [
      {
        id: "germany-2gb-7d",
        name: "Germany 2GB – 7 Days",
        price: 6,
        data: "2GB",
        validity: "7 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Instant activation", "No roaming charges"],
      },
      {
        id: "germany-5gb-15d",
        name: "Germany 5GB – 15 Days",
        price: 12,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Reliable coverage", "No roaming charges", "Most popular"],
      },
      {
        id: "germany-10gb-30d",
        name: "Germany 10GB – 30 Days",
        price: 20,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Best value", "No roaming charges", "24/7 support"],
      },
      {
        id: "germany-unlimited-30d",
        name: "Germany Unlimited – 30 Days",
        price: 35,
        data: "Unlimited",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Unlimited data", "Premium networks", "24/7 support"],
      },
    ],
  },
  europe: {
    name: "Europe",
    flag: "🇪🇺",
    type: "region",
    region: "Multi-Country",
    description:
      "Travel across Europe with one eSIM. Covers 28 countries with seamless connectivity.",
    coverage: "28 European countries",
    network: "Local premium networks in each country",
    startingFrom: 25,
    plansCount: 5,
    countries: [
      "Austria",
      "Belgium",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
    ],
    plans: [
      {
        id: "europe-5gb-15d",
        name: "Europe 5GB – 15 Days",
        price: 25,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["28 countries", "Instant activation", "No roaming charges"],
      },
      {
        id: "europe-10gb-30d",
        name: "Europe 10GB – 30 Days",
        price: 35,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "28 countries",
          "Instant activation",
          "No roaming charges",
          "Most popular",
        ],
      },
      {
        id: "europe-20gb-30d",
        name: "Europe 20GB – 30 Days",
        price: 50,
        data: "20GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: [
          "28 countries",
          "Instant activation",
          "No roaming charges",
          "Best value",
        ],
      },
      {
        id: "europe-30gb-60d",
        name: "Europe 30GB – 60 Days",
        price: 70,
        data: "30GB",
        validity: "60 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Extended validity", "No roaming charges", "24/7 support"],
      },
      {
        id: "europe-unlimited-30d",
        name: "Europe Unlimited – 30 Days",
        price: 90,
        data: "Unlimited",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Unlimited data", "All 28 countries", "Premium networks"],
      },
    ],
  },
  asiaPacific: {
    name: "Asia Pacific",
    flag: "🌏",
    type: "region",
    region: "Multi-Country",
    description:
      "Stay connected across 15 Asia Pacific countries with one eSIM.",
    coverage: "15 countries included",
    network: "Local premium networks in each country",
    startingFrom: 30,
    plansCount: 3,
    countries: [
      "Japan",
      "South Korea",
      "Singapore",
      "Thailand",
      "Malaysia",
      "Vietnam",
      "Philippines",
      "Hong Kong",
      "Taiwan",
      "India",
      "Indonesia",
      "Cambodia",
      "Laos",
      "Myanmar",
      "Sri Lanka",
    ],
    plans: [
      {
        id: "apac-5gb-15d",
        name: "Asia Pacific 5GB – 15 Days",
        price: 30,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["15 countries", "Instant activation", "No roaming charges"],
      },
      {
        id: "apac-10gb-30d",
        name: "Asia Pacific 10GB – 30 Days",
        price: 45,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["15 countries", "Instant activation", "Most popular"],
      },
      {
        id: "apac-20gb-30d",
        name: "Asia Pacific 20GB – 30 Days",
        price: 70,
        data: "20GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Best value", "No roaming charges", "24/7 support"],
      },
    ],
  },
  middleEast: {
    name: "Middle East",
    flag: "🕌",
    type: "region",
    region: "Multi-Country",
    description:
      "Travel seamlessly across the Middle East with one eSIM covering 12 countries.",
    coverage: "12 countries included",
    network: "Local premium networks in each country",
    startingFrom: 20,
    plansCount: 4,
    countries: [
      "UAE",
      "Saudi Arabia",
      "Qatar",
      "Oman",
      "Kuwait",
      "Bahrain",
      "Jordan",
      "Lebanon",
      "Egypt",
      "Turkey",
      "Israel",
      "Iraq",
    ],
    plans: [
      {
        id: "me-3gb-7d",
        name: "Middle East 3GB – 7 Days",
        price: 20,
        data: "3GB",
        validity: "7 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["12 countries", "Instant activation", "No roaming charges"],
      },
      {
        id: "me-5gb-15d",
        name: "Middle East 5GB – 15 Days",
        price: 28,
        data: "5GB",
        validity: "15 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["12 countries", "No roaming charges", "Most popular"],
      },
      {
        id: "me-10gb-30d",
        name: "Middle East 10GB – 30 Days",
        price: 40,
        data: "10GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Best value", "24/7 support", "Premium networks"],
      },
      {
        id: "me-20gb-30d",
        name: "Middle East 20GB – 30 Days",
        price: 65,
        data: "20GB",
        validity: "30 Days",
        speed: "4G/5G",
        hotspot: true,
        features: ["Extended usage", "No roaming charges", "24/7 support"],
      },
    ],
  },
} as any;

type Props = {
  params: { slug: string };
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const plan = planData[params.slug as keyof typeof planData];

  if (!plan) {
    return {
      title: "Plan Not Found – WaoSim",
    };
  }

  return {
    title: `Buy eSIM for ${plan.name} – WaoSim`,
    description: `Get the best eSIM data plans for ${plan.name}. Instant activation, affordable pricing, and reliable coverage.`,
  };
}

export default function PlanDetails({ params }: Props) {
  const plan = planData[params.slug as keyof typeof planData];

  if (!plan) {
    notFound();
  }

  return <PlanDetailsPage plan={plan} />;
}

export async function generateStaticParams() {
  return Object.keys(planData).map((slug) => ({
    slug,
  }));
}
